// packages/ui/src/Button.tsx
'use client';

import * as React from 'react';
import { motion, HTMLMotionProps } from 'framer-motion';

export interface ButtonProps extends Omit<HTMLMotionProps<'button'>, 'ref' | 'children'> {
  variant?: 'primary' | 'secondary' | 'outline' | 'danger' | 'ghost';
  size?: 'sm' | 'md' | 'lg';
  isLoading?: boolean;
  loadingText?: string;
  leftIcon?: React.ReactNode;
  rightIcon?: React.ReactNode;
  fullWidth?: boolean;
  children?: React.ReactNode;
}

const variantStyles = {
  primary:
    'bg-indigo-600 text-white hover:bg-indigo-700 border-transparent shadow-[0_4px_12px_rgba(79,70,229,0.2)]',
  secondary:
    'bg-zinc-100 dark:bg-zinc-800 text-zinc-900 dark:text-zinc-100 hover:bg-zinc-200 dark:hover:bg-zinc-700 border-transparent',
  outline:
    'bg-transparent border-zinc-200 dark:border-zinc-700 text-zinc-900 dark:text-zinc-100 hover:bg-zinc-50 dark:hover:bg-zinc-800/50',
  danger:
    'bg-rose-500 text-white hover:bg-rose-600 border-transparent shadow-[0_4px_12px_rgba(244,63,94,0.2)]',
  ghost:
    'bg-transparent text-zinc-600 dark:text-zinc-400 hover:text-zinc-900 dark:hover:text-zinc-100 hover:bg-zinc-100 dark:hover:bg-zinc-800 border-transparent',
};

const sizeStyles = {
  sm: 'px-3 py-1.5 text-xs rounded-lg min-h-[36px]',
  md: 'px-4 py-2.5 text-sm rounded-xl min-h-[44px]', // 44px min for mobile touch target
  lg: 'px-6 py-3.5 text-base rounded-2xl min-h-[52px]',
};

// High-end, clean circular loader spinner
function LoadingSpinner({ className }: { className?: string }) {
  return (
    <motion.svg
      className={`h-4.5 w-4.5 ${className}`}
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      animate={{ rotate: 360 }}
      transition={{ repeat: Infinity, duration: 0.75, ease: 'linear' }}
      aria-hidden="true"
    >
      <circle
        className="opacity-20"
        cx="12"
        cy="12"
        r="10"
        stroke="currentColor"
        strokeWidth="3.5"
      />
      <path
        className="opacity-80"
        fill="currentColor"
        d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
      />
    </motion.svg>
  );
}

export const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  (
    {
      children,
      className = '',
      variant = 'primary',
      size = 'md',
      isLoading = false,
      loadingText,
      leftIcon,
      rightIcon,
      fullWidth = false,
      disabled,
      ...props
    },
    ref
  ) => {
    const baseStyles =
      'inline-flex items-center justify-center gap-2 font-semibold transition-colors border outline-none active:scale-95 disabled:active:scale-100 select-none';
    const isActuallyDisabled = disabled || isLoading;

    return (
      <motion.button
        ref={ref}
        whileTap={isActuallyDisabled ? {} : { scale: 0.96 }}
        disabled={isActuallyDisabled}
        className={`
          ${baseStyles}
          ${variantStyles[variant]}
          ${sizeStyles[size]}
          ${fullWidth ? 'w-full' : ''}
          ${isActuallyDisabled ? 'opacity-50 cursor-not-allowed' : 'cursor-pointer'}
          ${className}
        `}
        aria-busy={isLoading}
        {...props}
      >
        {isLoading && <LoadingSpinner />}
        {!isLoading && leftIcon}

        {/* Button Content */}
        <span>{isLoading && loadingText ? loadingText : children}</span>

        {!isLoading && rightIcon}
      </motion.button>
    );
  }
);

Button.displayName = 'Button';

// src/app/shared/ui/button/button.component.ts
import { Component, input, output, ChangeDetectionStrategy } from '@angular/core';
import { NgClass } from '@angular/common';

@Component({
  selector: 'app-button',
  standalone: true,
  imports: [NgClass],
  template: `
    <button
      [type]="type()"
      [disabled]="isLoading()"
      (click)="clicked.emit()"
      class="w-full font-bold tracking-widest uppercase transition-all duration-200 active:scale-95 flex justify-center items-center gap-2 touch-manipulation focus:outline-none focus:ring-0 px-4 py-3 min-h-[48px] rounded-xl shadow-md disabled:opacity-70 disabled:cursor-not-allowed disabled:active:scale-100 text-[11px]"
      [ngClass]="isGoogle() ? 'bg-white text-gray-700 hover:bg-gray-50 border border-gray-200 shadow-sm' : 'bg-black text-white hover:bg-gray-900 shadow-black/20'"
    >
      @if (isLoading()) {
        <svg
          class="animate-spin -ml-1 mr-2 h-4 w-4 text-current"
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
        >
          <circle
            class="opacity-25"
            cx="12"
            cy="12"
            r="10"
            stroke="currentColor"
            stroke-width="4"
          ></circle>
          <path
            class="opacity-75"
            fill="currentColor"
            d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
          ></path>
        </svg>
        Loading...
      } @else {
        <!-- Colorful Google Icon -->
        @if (isGoogle()) {
          <svg class="w-5 h-5 mr-2" viewBox="0 0 48 48" xmlns="http://www.w3.org/2000/svg">
            <path
              fill="#EA4335"
              d="M24 9.5c3.54 0 6.71 1.22 9.21 3.6l6.85-6.85C35.9 2.38 30.47 0 24 0 14.62 0 6.51 5.38 2.56 13.22l7.98 6.19C12.43 13.72 17.74 9.5 24 9.5z"
            />
            <path
              fill="#4285F4"
              d="M46.98 24.55c0-1.57-.15-3.09-.38-4.55H24v9.02h12.94c-.58 2.96-2.26 5.48-4.78 7.18l7.73 6c4.51-4.18 7.09-10.36 7.09-17.65z"
            />
            <path
              fill="#FBBC05"
              d="M10.53 28.59c-.48-1.45-.76-2.99-.76-4.59s.27-3.14.76-4.59l-7.98-6.19C.92 16.46 0 20.12 0 24c0 3.88.92 7.54 2.56 10.78l7.97-6.19z"
            />
            <path
              fill="#34A853"
              d="M24 48c6.48 0 11.93-2.13 15.89-5.81l-7.73-6c-2.15 1.45-4.92 2.3-8.16 2.3-6.26 0-11.57-4.22-13.47-9.91l-7.98 6.19C6.51 42.62 14.62 48 24 48z"
            />
          </svg>
        }
        {{ text() }}
      }
    </button>
  `,
  changeDetection: ChangeDetectionStrategy.Default,
  styles: ``,
})
export class Button {
  text = input.required<string>();
  type = input<'button' | 'submit' | 'reset'>('button');
  isLoading = input<boolean>(false);
  isGoogle = input<boolean>(false);

  clicked = output<void>();
}
